"use client";
import { useMemo, useState } from "react";
import { membershipPlans } from "@/src/config/business";
import { track } from "@/src/lib/analytics";

type FormData = { firstName:string; lastName:string; email:string; phone:string; address:string; city:string; state:string; zip:string; vehicle:string; fuel:string; plan:string };
const initial: FormData = { firstName:"", lastName:"", email:"", phone:"", address:"", city:"", state:"SC", zip:"", vehicle:"", fuel:"Regular Unleaded", plan:"cruise-control" };

export function EnrollmentFlow() {
  const [step,setStep]=useState(1); const [form,setForm]=useState(initial); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<{memberNumber:string;activatedAt:string}|null>(null);
  const plan=useMemo(()=>membershipPlans.find(p=>p.id===form.plan)!,[form.plan]);
  const change=(key:keyof FormData)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm({...form,[key]:e.target.value});
  const next=()=>{ setError(""); if(step===1 && (!form.firstName||!form.lastName||!form.email||!form.phone)) return setError("Complete every customer field to continue."); if(step===2 && (!form.address||!form.city||!form.zip||!form.vehicle)) return setError("Complete the required service details to continue."); if(step===1) track("membership_started"); setStep(step+1); };
  async function pay() { setBusy(true); setError(""); try { const response=await fetch("/api/memberships/enroll",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,simulate:"success"})}); const data=await response.json() as {memberNumber:string;activatedAt:string;error?:string}; if(!response.ok) throw new Error(data.error||"Payment could not be confirmed."); setResult(data); track("membership_completed",{plan:form.plan}); setStep(5); } catch(e){setError(e instanceof Error?e.message:"Payment failed");track("membership_payment_failed");} finally{setBusy(false);} }
  if(step===5 && result) return <section className="confirmation"><span className="active-badge">ACTIVE</span><p className="eyebrow">PAYMENT CONFIRMED</p><h1>Welcome — Your Membership Is Active</h1><p>Your staff-visible membership record is ready now. No overnight reconciliation required.</p><dl><div><dt>Customer</dt><dd>{form.firstName} {form.lastName}</dd></div><div><dt>Membership ID</dt><dd>{result.memberNumber}</dd></div><div><dt>Plan</dt><dd>{plan.name}</dd></div><div><dt>Activated</dt><dd>{new Date(result.activatedAt).toLocaleString()}</dd></div><div><dt>Email</dt><dd>{form.email}</dd></div><div><dt>Service address</dt><dd>{form.address}, {form.city}, {form.state} {form.zip}</dd></div></dl><div className="hero-actions"><a className="button primary" href="/portal">Open member portal</a><a className="button secondary" href="/admin">See it in admin</a></div></section>;
  return <div className="enrollment-shell"><aside><p className="eyebrow">MEMBERSHIP ENROLLMENT</p><h2>Customer joins.<br/>Payment confirms.<br/><em>Membership activates.</em></h2><ol>{["Customer information","Service information","Membership plan","Secure payment"].map((label,i)=><li key={label} className={step===i+1?"current":step>i+1?"done":""}><span>{step>i+1?"✓":i+1}</span>{label}</li>)}</ol><div className="instant-note"><strong>No nightly batch.</strong><span>Activation is tied to verified server-side payment confirmation.</span></div></aside><section className="enrollment-card">
    <div className="step-label">STEP {step} OF 4</div>
    {step===1&&<><h3>Tell us about you</h3><p>We’ll use this information for your membership and delivery updates.</p><div className="form-grid"><label>First name<input value={form.firstName} onChange={change("firstName")} autoComplete="given-name"/></label><label>Last name<input value={form.lastName} onChange={change("lastName")} autoComplete="family-name"/></label><label>Email<input type="email" value={form.email} onChange={change("email")} autoComplete="email"/></label><label>Phone<input value={form.phone} onChange={change("phone")} autoComplete="tel" placeholder="(803) 555-0100"/></label></div></>}
    {step===2&&<><h3>Where should we fuel?</h3><p>Vehicles must be safely accessible to the delivery truck.</p><div className="form-grid"><label className="full">Service address<input value={form.address} onChange={change("address")} autoComplete="street-address"/></label><label>City<input value={form.city} onChange={change("city")} autoComplete="address-level2"/></label><label>State<input value={form.state} onChange={change("state")} autoComplete="address-level1"/></label><label>ZIP<input value={form.zip} onChange={change("zip")} autoComplete="postal-code"/></label><label>Vehicle + tag<input value={form.vehicle} onChange={change("vehicle")} placeholder="Blue Accord · ABC 123"/></label><label>Fuel type<select value={form.fuel} onChange={change("fuel")}><option>Regular Unleaded</option><option>Premium</option><option>Diesel</option></select></label></div></>}
    {step===3&&<><h3>Choose your plan</h3><p>Fuel is billed separately at the daily rate. Members save $0.10 per gallon.</p><div className="plan-options">{membershipPlans.map(p=><label key={p.id} className={form.plan===p.id?"selected":""}><input type="radio" name="plan" value={p.id} checked={form.plan===p.id} onChange={change("plan")}/><div><b>{p.name}</b><span>{p.vehicles} vehicle{p.vehicles>1?"s":""} · {p.fillUps} fill-ups/month</span></div><strong>${p.monthlyPrice}<small>/mo</small></strong></label>)}</div><p className="fine-print">Memberships renew monthly. Cancel at least five days before the next billing date. Demonstration checkout only.</p></>}
    {step===4&&<><h3>Confirm your membership</h3><p>This demo simulates an immediate processor confirmation and verified webhook.</p><div className="payment-demo"><span>DEMO CARD</span><label>Card number<input value="4242 4242 4242 4242" readOnly/></label><div><label>Expiration<input value="12 / 30" readOnly/></label><label>CVC<input value="123" readOnly/></label></div></div><div className="order-summary"><span>{plan.name} monthly membership</span><strong>${plan.monthlyPrice}.00 today</strong></div><label className="check"><input type="checkbox" required defaultChecked/> I agree to recurring monthly billing and the membership terms.</label></>}
    {error&&<p className="form-error" role="alert">{error}</p>}
    <div className="form-actions">{step>1&&<button className="button secondary" onClick={()=>setStep(step-1)} disabled={busy}>Back</button>}<button className="button primary" onClick={step===4?pay:next} disabled={busy}>{busy?"Confirming payment…":step===4?`Pay $${plan.monthlyPrice}.00 & activate`:"Continue →"}</button></div>
  </section></div>;
}
