import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
const timestamps = { createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() };
export const users = sqliteTable("users", { id:text("id").primaryKey(), externalAuthId:text("external_auth_id").notNull(), email:text("email").notNull(), role:text("role",{enum:["customer","staff","admin"]}).notNull(), ...timestamps }, t=>[uniqueIndex("idx_users_external_auth").on(t.externalAuthId),index("idx_users_email").on(t.email)]);
export const leadSources = sqliteTable("lead_sources", { id:text("id").primaryKey(), name:text("name").notNull(), ...timestamps }, t=>[uniqueIndex("idx_lead_sources_name").on(t.name)]);
export const customers = sqliteTable("customers", { id:text("id").primaryKey(), userId:text("user_id").references(()=>users.id), firstName:text("first_name").notNull(), lastName:text("last_name").notNull(), email:text("email").notNull(), phone:text("phone").notNull(), leadSourceId:text("lead_source_id").references(()=>leadSources.id), tags:text("tags",{mode:"json"}).$type<string[]>().notNull().default([]), lastActivityAt:text("last_activity_at"), ...timestamps }, t=>[index("idx_customers_email").on(t.email),index("idx_customers_phone").on(t.phone),index("idx_customers_name").on(t.lastName,t.firstName)]);
export const addresses = sqliteTable("addresses", { id:text("id").primaryKey(), customerId:text("customer_id").notNull().references(()=>customers.id), type:text("type",{enum:["service","billing"]}).notNull(), line1:text("line1").notNull(), line2:text("line2"), city:text("city").notNull(), state:text("state").notNull(), zip:text("zip").notNull(), ...timestamps }, t=>[index("idx_addresses_customer").on(t.customerId),index("idx_addresses_zip").on(t.zip)]);
export const membershipPlans = sqliteTable("membership_plans", { id:text("id").primaryKey(), slug:text("slug").notNull(), name:text("name").notNull(), monthlyPriceCents:integer("monthly_price_cents").notNull(), includedVehicles:integer("included_vehicles").notNull(), includedFillUps:integer("included_fill_ups").notNull(), active:integer("active",{mode:"boolean"}).notNull().default(true), ...timestamps }, t=>[uniqueIndex("idx_membership_plans_slug").on(t.slug)]);
export const memberships = sqliteTable("memberships", { id:text("id").primaryKey(), memberNumber:text("member_number").notNull(), customerId:text("customer_id").notNull().references(()=>customers.id), planId:text("plan_id").notNull().references(()=>membershipPlans.id), status:text("status",{enum:["pending_payment","active","past_due","canceled","expired"]}).notNull(), currentPeriodStart:text("current_period_start"), currentPeriodEnd:text("current_period_end"), activatedAt:text("activated_at"), canceledAt:text("canceled_at"), externalSubscriptionId:text("external_subscription_id"), ...timestamps }, t=>[uniqueIndex("idx_memberships_member_number").on(t.memberNumber),index("idx_memberships_customer").on(t.customerId),index("idx_memberships_status").on(t.status)]);
export const payments = sqliteTable("payments", { id:text("id").primaryKey(), membershipId:text("membership_id").notNull().references(()=>memberships.id), provider:text("provider").notNull(), externalPaymentId:text("external_payment_id").notNull(), amountCents:integer("amount_cents").notNull(), currency:text("currency").notNull().default("usd"), status:text("status",{enum:["pending","processing","succeeded","failed","refunded","canceled"]}).notNull(), errorMessage:text("error_message"), processedAt:text("processed_at"), ...timestamps }, t=>[uniqueIndex("idx_payments_external").on(t.externalPaymentId),index("idx_payments_membership").on(t.membershipId),index("idx_payments_status_created").on(t.status,t.createdAt)]);
export const paymentEvents = sqliteTable("payment_events", { id:text("id").primaryKey(), paymentId:text("payment_id").references(()=>payments.id), provider:text("provider").notNull(), externalEventId:text("external_event_id").notNull(), eventType:text("event_type").notNull(), payload:text("payload",{mode:"json"}).$type<Record<string,unknown>>().notNull(), processedAt:text("processed_at"), createdAt:text("created_at").notNull() }, t=>[uniqueIndex("idx_payment_events_external").on(t.provider,t.externalEventId),index("idx_payment_events_payment").on(t.paymentId)]);
export const serviceRequests = sqliteTable("service_requests", { id:text("id").primaryKey(), customerId:text("customer_id").references(()=>customers.id), name:text("name").notNull(), email:text("email").notNull(), phone:text("phone").notNull(), address:text("address").notNull(), requestType:text("request_type").notNull(), preferredDate:text("preferred_date"), notes:text("notes"), status:text("status",{enum:["new","contacted","scheduled","completed","canceled"]}).notNull().default("new"), ...timestamps }, t=>[index("idx_service_requests_status_created").on(t.status,t.createdAt),index("idx_service_requests_customer").on(t.customerId)]);
export const customerNotes = sqliteTable("customer_notes", { id:text("id").primaryKey(), customerId:text("customer_id").notNull().references(()=>customers.id), authorUserId:text("author_user_id").references(()=>users.id), body:text("body").notNull(), createdAt:text("created_at").notNull() }, t=>[index("idx_customer_notes_customer_created").on(t.customerId,t.createdAt)]);
export const activityEvents = sqliteTable("activity_events", { id:text("id").primaryKey(), customerId:text("customer_id").references(()=>customers.id), membershipId:text("membership_id").references(()=>memberships.id), type:text("type").notNull(), summary:text("summary").notNull(), metadata:text("metadata",{mode:"json"}).$type<Record<string,unknown>>().notNull().default({}), createdAt:text("created_at").notNull() }, t=>[index("idx_activity_customer_created").on(t.customerId,t.createdAt),index("idx_activity_membership_created").on(t.membershipId,t.createdAt)]);

